export const BASE_URL = 'http://localhost:3000'; // TODO: Fetch from react app params
export const IDP_URL = 'http://localhost:4000'; // TODO: Fetch from react app params or user choice
export const AUTH_ENDPOINT = '/oidc/auth'; // TODO: Discover this endpoint via resource: ${idpUrl}/.well-known/openid-configuration.
export const TOKEN_ENDPOINT = '/oidc/token'; // TODO: Discover this endpoint via resource: ${idpUrl}/.well-known/openid-configuration.
export const CLIENT_ID = process.env.NEXT_PUBLIC_CLIENT_ID || false;
export const CLIENT_SECRET = process.env.REACT_APP_CLIENT_SECRET || false;
export const RESPONSE_TYPE = 'code'; // TODO: Fetch from react app params
export const SCOPE = 'openid'; // TODO: Fetch from react app params
export const TOKEN_URL = `${IDP_URL}${TOKEN_ENDPOINT}`;
