name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Install deps and lint
        shell: bash
        run: |
          yarn install --frozen-lockfile
          yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Install deps and test
        shell: bash
        run: |
          yarn install --frozen-lockfile
          yarn test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Install deps and build
        shell: bash
        run: |
          yarn install --frozen-lockfile
          yarn build
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Install test (ignore coverage threshold)
        shell: bash
        run: |
          yarn install --frozen-lockfile
          yarn test --coverageThreshold '{}'
      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
